model:
  input_shape: [128, 128, 3]
  num_classes: 1

patient:
  early_stop: 8
  reduce_lr_plateau: 4

training:
  epochs: 1
  batch_size: 2
  valid_size: 0.01
  train_size: 0.1
  learning_rate: 0.0001

paths:
  train_dir: "datasets/train"
  valid_dir: "datasets/valid"
  images_dir: "images"
  datasets_dir: "datasets/"
